### ISSUE TITLE
The ABNF for did:tdw seems to be missing the optional percent encoding of the port in the http url

### ISSUE THREAD

**Issue by daidoji** [decentralized-identity/trustdidweb#111]
> tdw-did = "did:tdw:" scid ":" domain-segment 1+( "." domain-segment ) *( ":" path-segment )
>domain-segment = ; A part of a domain name as defined in RFC3986, such as "example" and "com" in "example.com"
>path-segment= ; A part of a URL path as defined in RFC3986, such as "path", "to", "folder" in "path/to/folder"

Probably just needs a percent encoded optional ABNF snippet between the domain-segments and path-segments.

**Comment by swcurran** [comment]
Good catch. Will add that after the current 0.4 PR is merged.

**Comment by swcurran** [comment]
Action: Add this as a clarification without changing the version. @swcurran
