### ISSUE TITLE
It may be better to enforce a normative requirement that the versionTime require a UTC offset

### ISSUE THREAD

**Issue by daidoji** [decentralized-identity/trustdidweb#112]
From the spec we have the two normative requirements:

>2. The value of versionTime MUST be a timestamp of the entry in [ISO8601](http://localhost:8000/#term:iso8601) format, as asserted by the [DID Controller](http://localhost:8000/#term:did-controller). The timestamp MUST be the time the DID will be retrieved by a [witness](http://localhost:8000/#term:witness) or resolver, or before.

In order to prevent ambiguity or state conditions between funny time differentials in witnesses and resolvers and controllers that may exist in different time zones, it may be a good idea to not only follow ISO8601 but to require enforcement of mandatory offsets mentioned in the 8601 spec or that all actors resolve the diddoc in UTC.

**Comment by swcurran** [comment]
Added to the 0.4 PR currently in process.  Thanks — good guidance.

**Comment by brianorwhatever** [comment]
Completed in #108
