### ISSUE TITLE
Is VersionId in the example in Generate Entry Hash (#generate-entry-hash) is missing its index in string?

### ISSUE THREAD

**Issue by daidoji** [decentralized-identity/trustdidweb#113]
In the **Generate Entry Hash** section 4.7.3 we have the example

```{"versionId": "QmfGEUAcMpzo25kF2Rhn8L5FAXysfGnkzjwdKoNPi615XQ", "versionTime": "2024-09-26T23:22:26Z", "parameters": {"prerotation": true, "updateKeys": ["z6MkhbNRN2Q9BaY9TvTc2K3izkhfVwgHiXL7VWZnTqxEvc3R"], "nextKeyHashes": ["QmXC3vvStVVzCBHRHGUsksGxn6BNmkdETXJGDBXwNSTL33"], "method": "did:tdw:0.4", "scid": "QmfGEUAcMpzo25kF2Rhn8L5FAXysfGnkzjwdKoNPi615XQ"}, "state": {"@context": ["https://www.w3.org/ns/did/v1"], "id": "did:tdw:QmfGEUAcMpzo25kF2Rhn8L5FAXysfGnkzjwdKoNPi615XQ:domain.example"}}```

Shouldn't the `versionId` start with a number and a `-` in this example?

**Comment by daidoji** [comment]
This actually happens in the examples in the appendix as well.

**Comment by daidoji** [comment]
Oh wait, closing because I see that the `1-` is added afterwards in the first event generated, but is included (because the spec just uses the previous versionId) in all subsequent chaining.

**Comment by swcurran** [comment]
I think we do need to be more precise about saying — “This is the SCID calculation input”, “This is the entry hash generation input”, and “This is the proof generation input”.  In the case you are pointing out, that is the entry hash generation input for the first version.
