### ISSUE TITLE
Add the rendering of older specification version

### ISSUE THREAD

**Issue by bj-ms** [decentralized-identity/trustdidweb#119]
It would be great to add the rendering of previous versions of the specification like Presentation Exchange does: https://identity.foundation/presentation-exchange/

It allows to link back to older versions of the specification without having to guess the older content from the changelog chapter or render it yourself from older commits.

It will be important for interoperability later on and can help to differentiate the current implementations of did:tdw.

**Comment by swcurran** [comment]
I’ve done this for [mkdocs material] website, but this is not currently supported for Spec-Up — the tool we’re using to generate the website.  I’ve put in a [Spec-Up issue](https://github.com/decentralized-identity/spec-up/issues/67) to see if a similar approach can be taken, but I’m not overly hopeful.

I’m going to see if we can make a fork of this repo and publish the v0.3 spec from the fork.  Not very scalable, but I guess it would do...

**Comment by swcurran** [comment]
I saw able to create a [fork](https://github.com/decentralized-identity/trustdidweb-v03], a [branch in that fork](https://github.com/decentralized-identity/trustdidweb-v03/tree/v0.3], and use that to publish the v0.3 spec to: [https://identity.foundation/trustdidweb-v03](https://identity.foundation/trustdidweb-v03/).

I'll add a link to the version.md file to the rendered version of the spec.

I'm also going to try limit who can do what on the fork -- it's a messy path if we start making changes to it.

Hopefully we don't have to do this too often, but for now we have an approach.

**Comment by swcurran** [comment]
Learned about the right way to do this.  Spec-Up supports multiple specs from a single base by having the "main" spec (current), and snapshots of the spec content for each version.  I'll implement that in the next couple of days.

**Comment by swcurran** [comment]
Resolved this with PR #121 .  As noted, this is a built-in feature of Spec-Up, and I’ve added instructions on how to do this to the Readme for future versions.
