### ISSUE TITLE
Solving for heavy identifier length with Compatibility URLs

### ISSUE THREAD

**Issue by erlend-sh** [decentralized-identity/trustdidweb#130]
Feel free to close if irrelevant (I would’ve put it in Discussions if I could) but I just found this note from another DID project somewhat interesting:

> did:tdw carries a heavy identifier length, while did:fedi with Compatibility URLs carries the same benefits, with less overhead

https://arcanican.is/excerpts/did-method-fedi/#compat

**Comment by andrewwhitehead** [comment]
I wouldn't say it carries the same benefits. It's not clear to me from scanning the spec how one actually resolves a `did:fedi`, there's a section on submission and retrieval but it doesn't say what service it's interacting with. `did:tdw` does not rely on any external services for resolution and so the identifier includes the location as well as the SCID.

There's no examples in the spec but it appears a compatibility URL would be of the form:

    https://example.domain/did:fedi:z6x5vHr6sWxo4qtYamucHWRuug

If we use the `did:tdw` syntax this would be 8 characters shorter:

    did:fedi:z6x5vHr6sWxo4qtYamucHWRuug:example.domain

An earlier draft of `did:tdw` also supported a `length` parameter to limit the size of the SCID but we decided it wasn't worth the impact on the collision resistance.

The current instructions for handling a compatibility URL also seem like a great phishing opportunity. It only requires that the retrieved DID document include the resolution hint (the URL prefix) as an `alsoKnownAs`, which is only a one-way attestation. That means that I can seemingly publish a `did:fedi` with an `alsoKnownAs` of a popular website and then impersonate that site through these URLs.
