### ISSUE TITLE
Drop Patch support

### ISSUE THREAD

**Issue by TelegramSam** [decentralized-identity/trustdidweb#64]
I know this has been discussed elsewhere, but adding issue for clarity.

I think the complexity of patch isn't worth the benefits it brings. If each entry is just a new full DID Document, it is a much simpler solution.

**Comment by brianorwhatever** [comment]
Yeah we have been discussing this as we are noticing patches aren't actually less data in the examples we have used. We think maybe our jsonpatch implementations aren't the most performant and could be doing things a bit smarter. We also want to run tests with large diddocs to see the comparisons.. more testing needed.

**Comment by brianorwhatever** [comment]
This change was made in version 0.4 in #108
