### ISSUE TITLE
Use a "Proof Chain" for witness proofs

### ISSUE THREAD

**Issue by brianorwhatever** [decentralized-identity/trustdidweb#66]
As shown [here](https://www.w3.org/TR/vc-data-integrity/#proof-chains) I think it might be a good idea to include the `previousProof` property to a witness proof. This will show that the witnesses are signing on top of an already signed proof by the controller. It will also give us a simple way to know which proofs to remove from the log entry when creating a new one.

**Comment by swcurran** [comment]
Nice! I like that. I’ll see about updating the spec. to include that.

**Comment by brianorwhatever** [comment]
We determined not to do this for now
